In [1]:
import pandas as pd 
import pickle
from textblob import TextBlob,Word

In [2]:
def load_obj(name ):
    with open( 'files/'+name + '.pkl', 'rb') as f:
        return pickle.load(f)

In [3]:
def getReview(res_id):
    reviews = []
    rev = df[(df['restaurant_id']==res_id) & (df['useful']>0)]['review']
    for r in rev:
        reviews.append(r)
    return reviews

In [4]:
def getPrediction(id):
    rev= getReview(id)
    food_count = 0 
    serv_count = 0
    amb_count = 0
    deal_count = 0

    for review in rev:
        prediction = {}
        prediction["food"] = food_classifier.predict([review])[0]
        prediction["service"] = service_classifier.predict([review])[0]
        prediction["amb"] = amb_classifier.predict([review])[0]
        prediction["deals"] = deal_classifier.predict([review])[0]

        if(prediction["food"]==1):
            food_count += 1
        if(prediction["service"]==1):
            serv_count += 1
        if(prediction["amb"]==1):
            amb_count += 1
        if(prediction["deals"]==1):
            deal_count += 1

    #     print(prediction)

    rev_size = len(rev)
    if(rev_size> 0 ):
        food_per = food_count/rev_size*100
        serv_per = serv_count/rev_size*100
        amb_per = amb_count/rev_size*100
        deal_per = deal_count/rev_size*100
    else:
        food_per= 0 
        serv_per=0
        amb_per=0
        deal_per=0 

    # print(rev_size,food_per,serv_per,amb_per,deal_per)
    return (rev_size,food_per,serv_per,amb_per,deal_per)

In [5]:
def stemming_tokenizer(text):
    stopwords = []
    with open('files/new_sw.txt','r+') as f:
        stopword = f.readlines()
        for sw in stopword:
            sw = sw[:-1]
            stopwords.append(sw)
    f.close()
    text = text.lower()
    words = TextBlob(text).correct().words
    words = [Word(w).lemmatize("v") for w in words if not w in stopwords]
    return words

In [6]:
df = pd.read_csv('files/reviews.csv', encoding = "ISO-8859-1")

In [7]:
food_classifier= load_obj('food_classifier')
service_classifier= load_obj('service_classifier')
amb_classifier= load_obj('amb_classifier')
deal_classifier= load_obj('deal_classifier')

C:\Users\acer\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator CountVectorizer from version 0.18.2 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\acer\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator TfidfTransformer from version 0.18.2 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\acer\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator KNeighborsClassifier from version 0.18.2 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)
C:\Users\acer\Anaconda3\lib\site-packages\sklearn\base.py:315: UserWarning: Trying to unpickle estimator Pipeline from version 0.18.2 when using version 0.18.1. This might lead to breaking code or invalid results. Use at your own risk.
  UserWarning)

In [9]:
pred= pd.read_csv('files/prediction.csv',encoding="ISO-8859-1")

In [ ]:
for id in pred[(pred['food']==-1)& (pred['restaurant_id']<101)].restaurant_id:
    i,a,b,c,d= getPrediction(id)
    pred.iloc[id-1,1]= a
    pred.iloc[id-1,2]= b 
    pred.iloc[id-1,3]= c 
    pred.iloc[id-1,4]= d 
    print(i,id,a,b,c,d)

In [19]:
pred.iloc[3300:]

      restaurant_id        food     service   ambience      deals
3300           3301   98.113208   33.018868   5.660377   0.000000
3301           3302  100.000000   28.571429   0.000000   0.000000
3302           3303   81.818182   18.181818   0.000000   6.060606
3303           3304   88.888889    0.000000   0.000000   0.000000
3304           3305  100.000000   16.666667   5.555556   0.000000
3305           3306  100.000000  100.000000   0.000000   0.000000
3306           3307   77.777778   44.444444  11.111111   0.000000
3307           3308  100.000000   66.666667   0.000000   0.000000
3308           3309   92.307692   30.769231   2.564103   2.564103
3309           3310   75.000000   12.500000   6.250000  12.500000
3310           3311   93.478261   30.434783   6.521739   6.521739
3311           3312  100.000000   20.000000  20.000000   0.000000
3312           3313   93.103448   24.137931   3.448276   6.896552
3313           3314  100.000000   23.076923  15.384615   0.000000
3314           3315  100.000000    8.333333  16.666667   0.000000
3315           3316  100.000000  100.000000   0.000000   0.000000
3316           3317  100.000000    0.000000   0.000000   0.000000
3317           3318   88.888889   44.444444   0.000000   0.000000
3318           3319    0.000000    0.000000   0.000000   0.000000
3319           3320  100.000000  100.000000   0.000000   0.000000
3320           3321   80.000000   60.000000   0.000000  20.000000
3321           3322   97.916667   47.916667   6.250000   0.000000
3322           3323   97.333333   24.000000  14.666667   1.333333
3323           3324  100.000000   36.842105   5.263158   0.000000
3324           3325   66.666667   33.333333   0.000000   0.000000
3325           3326   90.909091   27.272727   0.000000   0.000000
3326           3327   88.888889   22.222222  11.111111   0.000000
3327           3328   93.181818   45.454545   9.090909   4.545455
3328           3329   88.888889   11.111111   0.000000   0.000000
3329           3330  100.000000   50.000000   0.000000   0.000000
...             ...         ...         ...        ...        ...
4473           4474   -1.000000   -1.000000  -1.000000  -1.000000
4474           4475   -1.000000   -1.000000  -1.000000  -1.000000
4475           4476   -1.000000   -1.000000  -1.000000  -1.000000
4476           4477   -1.000000   -1.000000  -1.000000  -1.000000
4477           4478   -1.000000   -1.000000  -1.000000  -1.000000
4478           4479   -1.000000   -1.000000  -1.000000  -1.000000
4479           4480   -1.000000   -1.000000  -1.000000  -1.000000
4480           4481   -1.000000   -1.000000  -1.000000  -1.000000
4481           4482   -1.000000   -1.000000  -1.000000  -1.000000
4482           4483   -1.000000   -1.000000  -1.000000  -1.000000
4483           4484   -1.000000   -1.000000  -1.000000  -1.000000
4484           4485   -1.000000   -1.000000  -1.000000  -1.000000
4485           4486   -1.000000   -1.000000  -1.000000  -1.000000
4486           4487   -1.000000   -1.000000  -1.000000  -1.000000
4487           4488   -1.000000   -1.000000  -1.000000  -1.000000
4488           4489   -1.000000   -1.000000  -1.000000  -1.000000
4489           4490   -1.000000   -1.000000  -1.000000  -1.000000
4490           4491   -1.000000   -1.000000  -1.000000  -1.000000
4491           4492   -1.000000   -1.000000  -1.000000  -1.000000
4492           4493   -1.000000   -1.000000  -1.000000  -1.000000
4493           4494   -1.000000   -1.000000  -1.000000  -1.000000
4494           4495   -1.000000   -1.000000  -1.000000  -1.000000
4495           4496   -1.000000   -1.000000  -1.000000  -1.000000
4496           4497   -1.000000   -1.000000  -1.000000  -1.000000
4497           4498   -1.000000   -1.000000  -1.000000  -1.000000
4498           4499   -1.000000   -1.000000  -1.000000  -1.000000
4499           4500   -1.000000   -1.000000  -1.000000  -1.000000
4500           4501   -1.000000   -1.000000  -1.000000  -1.000000
4501           4502   -1.000000   -1.000000  -1.000000  -1.000000
4502           4503   -1.000000   -1.000000  -1.000000  -1.000000

[1203 rows x 5 columns]

In [25]:
pred.to_csv("files/prediction.csv", sep=',', encoding='utf-8',index=None)